### ISSUE TITLE
[feat]: Enable Monero XMR payments on BTCPay Server

### ISSUE THREAD

**Issue by brainchainz** [Start9Labs/btcpayserver-startos#48]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Now that EmbassyOS has a Monero node, let's get BTCPay Server XMR-enabled.

### Describe the Use Case

Vendors being able to accept BTC on-chain, lightning, and Monero. For examples checkout eataupa.com, they accept all 3.

**Comment by brainchainz** [comment]
Hello, is anyone available to work on this?

**Comment by elvece** [comment]
Hi @brainchainz sincerest apologies for the delay in response! I spaced 😅 Happy to say that I have been working on this and hope to have a beta release this week
